name: CI
on:
  push:
    branches: [main]
jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum yarn test
      - name: Build for GitHub pages
        run: |
          yarn build
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.1.4
        with:
          branch: gh-pages
          folder: build
